# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_auto_20171213_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
