# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_auto_20171213_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(blank=True, choices=[('M', 'Monday'), ('Tu', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thusrday'), ('F', 'Friday')], max_length=2, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('hours', models.DurationField(editable=False)),
                ('activated', models.BooleanField(default=False, verbose_name='Activate')),
                ('sale_status', models.BooleanField(default=False, verbose_name='Activate sale')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='shifts.Employee_profile')),
            ],
        ),
    ]
