# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_auto_20171213_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='hours',
        ),
    ]
