# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_remove_shift_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='prof_pic/'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='day_of_the_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thusrday'), ('Friday', 'Friday')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_name',
            field=models.CharField(blank=True, choices=[('Morning shift', 'Morning Shift'), ('Evening shift', 'Evening Shift'), ('Night shift', 'Night Shift')], max_length=10, null=True),
        ),
    ]
